name: Pharmaceutical Sales Prediction
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              Print results
          " > report.md
          cml send-comment report.md